// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function InspectFile(arg1) {
  return window['go']['main']['App']['InspectFile'](arg1);
}

export function IsElevated() {
  return window['go']['main']['App']['IsElevated']();
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function RelaunchElevated() {
  return window['go']['main']['App']['RelaunchElevated']();
}

export function ReleaseLocks(arg1, arg2) {
  return window['go']['main']['App']['ReleaseLocks'](arg1, arg2);
}
