// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {locklift} from '../models';

export function ClearRecentFiles():Promise<void>;

export function GetRecentFiles():Promise<Array<string>>;

export function InspectFile(arg1:string):Promise<locklift.InspectResult>;

export function IsElevated():Promise<boolean>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function PickFile():Promise<string>;

export function RelaunchElevated():Promise<void>;

export function ReleaseLocks(arg1:string,arg2:Array<number>):Promise<locklift.ReleaseResult>;
